code review
lukasorgovan/gitik pull request #3
Opened 2021-08-04 13:37 UTC by stanohlivjak

pull requst

2021-08-04 14:04 UTC, lukasorgovan commented
You have a conflict here :) please resolve conflict.

2021-08-04 14:13 UTC, lukasorgovan commented on Solution.class
> +        String temp = String.valueOf(x);
I am no Java expert, but what about using String builder class to create something 
https://www.javatpoint.com/StringBuilder-class

stringHalf = 1/2 string
secondHalf = 2/2 string - reversed
stringHalf === secondHalf  

of course you need to check odd numbered length of string :) just an idea.

2021-08-05 06:10 UTC, stanohlivjak commented
The conflict should be resolved.

2021-08-05 06:23 UTC, lukasorgovan requested changes
ok you are trying to remove README.md file, not sure why, but you should not be removing this file :) 
It is there to help you guys remember basic stuff :)

2021-08-05 11:27 UTC, stanohlivjak commented
I hope that everything is fixed now. :)

2021-08-05 11:35 UTC, merged